### Sync people (Amplify)
POST https://main.d2nen9gnvvgqeo.amplifyapp.com/api/sync/people
Content-Type: application/json

[
    {
        "person_id": 402848525526,
        "salutation": "Mr.",
        "first_name": "MILOS",
        "last_name": "MILJKOVIC",
        "nationality": "Greece",
        "mobile_phone": "6971582629",
        "email": "miljkovicmisa@gmail.com",
        "room_type": "double",
        "companion_full_name": "Maria Perdikaki",
        "companion_email": "perdikakimary@gmail.com",
        "checkin_date": "2026-04-22",
        "checkout_date": "2026-04-24",
        "comments": "test comment",
        "guest_type": "guest",
        "company": "Whitehat - Μακρής Αλκιβιάδης",
        "job_title": " Dev"
    }
]


### Sync people (Amplify)
POST https://main.d2nen9gnvvgqeo.amplifyapp.com/api/sync/people
Content-Type: application/json

{
  "email": "g.markantonatos@tsomokos.gr",
  "company": "Tsomokos Communications",
  "comments": "Test comment 1",
  "job_title": "Digital Operations Manager",
  "last_name": "Markantonatos",
  "person_id": 2402999758033,
  "room_type": "double",
  "first_name": "George",
  "guest_type": "guest",
  "salutation": "Mr.",
  "nationality": "Greece",
  "checkin_date": "2026-04-23",
  "mobile_phone": 2107289000,
  "checkout_date": "2026-04-24",
  "companion_email": "m.pylarinos@tsomokos.gr",
  "companion_full_name": "Michalis Pylarinos"
}

### Sync people (local)
POST http://localhost:3000/api/sync/people
Content-Type: application/json

[
    {
        "person_id": 402848525526,
        "salutation": "Mr.",
        "first_name": "MILOS",
        "last_name": "MILJKOVIC",
        "nationality": "Greece",
        "mobile_phone": "6971582629",
        "email": "miljkovicmisa@gmail.com",
        "room_type": "double",
        "companion_full_name": "Maria Perdikaki",
        "companion_email": "perdikakimary@gmail.com",
        "checkin_date": "2026-04-22",
        "checkout_date": "2026-04-24",
        "comments": "test comment",
        "guest_type": "guest",
        "company": "Whitehat - Μακρής Αλκιβιάδης",
        "job_title": " Dev"
    }
]


### Sync people (local)
POST http://localhost:3000/api/sync/people
Content-Type: application/json

{
  "email": "g.markantonatos@tsomokos.gr",
  "company": "Tsomokos Communications",
  "comments": "Test comment 3",
  "job_title": "Digital Operations Manager",
  "last_name": "Markantonatos",
  "person_id": 403546085605,
  "room_type": "double",
  "first_name": "George",
  "guest_type": "guest",
  "salutation": "Mr.",
  "nationality": "Greece",
  "checkin_date": "2026-04-23",
  "mobile_phone": 2107289000,
  "checkout_date": "2026-04-24",
  "companion_email": "m.pylarinos@tsomokos.gr",
  "companion_full_name": "Michalis Pylarinos"
}
